// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_UVJ9oP57fn8ZhN7POYZtbpR9BV3O5ag',
    appId: '1:809267349096:web:733c4c6d76deeef6f31ddd',
    messagingSenderId: '809267349096',
    projectId: 'rock-atlas-405800',
    authDomain: 'rock-atlas-405800.firebaseapp.com',
    storageBucket: 'rock-atlas-405800.firebasestorage.app',
    measurementId: 'G-E5XPGHV30X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8rOxS9BkruKl5tBVy1znLGjrDO6F1NVU',
    appId: '1:809267349096:android:9d3734430e8571d0f31ddd',
    messagingSenderId: '809267349096',
    projectId: 'rock-atlas-405800',
    storageBucket: 'rock-atlas-405800.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfK8G2IwatMzGPPSbCLxxvafkbkrqEniM',
    appId: '1:809267349096:ios:5f2b50e6f866584df31ddd',
    messagingSenderId: '809267349096',
    projectId: 'rock-atlas-405800',
    storageBucket: 'rock-atlas-405800.firebasestorage.app',
    iosBundleId: 'com.example.edutrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfK8G2IwatMzGPPSbCLxxvafkbkrqEniM',
    appId: '1:809267349096:ios:5f2b50e6f866584df31ddd',
    messagingSenderId: '809267349096',
    projectId: 'rock-atlas-405800',
    storageBucket: 'rock-atlas-405800.firebasestorage.app',
    iosBundleId: 'com.example.edutrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_UVJ9oP57fn8ZhN7POYZtbpR9BV3O5ag',
    appId: '1:809267349096:web:d19e89adfb976feff31ddd',
    messagingSenderId: '809267349096',
    projectId: 'rock-atlas-405800',
    authDomain: 'rock-atlas-405800.firebaseapp.com',
    storageBucket: 'rock-atlas-405800.firebasestorage.app',
    measurementId: 'G-VSWL46MVVX',
  );
}
